name: Update ECS Task Definition

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  update-task-definition:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials for use
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
      
    - name: Install AWS CLI and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli jq
    
    - name: Retrieve branch or tag name and update Parameter Store
      id: update-parameter-store
      run: |
        # Retrieve the branch or tag name
        BRANCH_OR_TAG=$(git rev-parse --abbrev-ref HEAD)
        
        # Update the parameter value in Parameter Store
        aws ssm put-parameter --name "container_tag-data-normalization" --value "$BRANCH_OR_TAG" --type String --overwrite
        
    - name: Update ECS Task Definition
      run: |
        # Define variables
        BRANCH_OR_TAG=$(git rev-parse --abbrev-ref HEAD)
        TASK_DEFINITION_ARN="arn:aws:ecs:us-east-1:475768992472:task-definition/auto-normalize-iz6m29xlzo8a770dbc180028ba90d9b2"
        NEW_IMAGE="475768992472.dkr.ecr.us-east-1.amazonaws.com/idscience/ecs-auto-normalize:$BRANCH_OR_TAG"
        # Retrieve the existing task definition
        aws ecs describe-task-definition \
            --task-definition "$TASK_DEFINITION_ARN" \
            --query 'taskDefinition' \
            --output json > task-def.json
        # Modify the image URL in the container definition
        jq --arg new_image "$NEW_IMAGE" '
        .containerDefinitions[0].image = $new_image |
        del(.revision, .status, .taskDefinitionArn, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
        ' task-def.json > updated-task-def.json
        # Register the new task definition
        aws ecs register-task-definition --cli-input-json file://updated-task-def.json
